### ISSUE TITLE
Scrolling Artists page on mobile results in unwanted link clicks

### ISSUE THREAD

**Issue by meljoann** [EmissarySocial/bandwagon#12]
First, thanks for this, we really need a Fedi music app!

I was trying to scroll through here:
 https://bandwagon.fm/artists

And unless my finger is on the very edge on the right, artist pages are inadvertently clicked. So it's not easy to browse artists.

Expected behaviour: a small area (artist photo and/or underlined name link) is the clickable link, the empty space on the page can be used for touchscreen scrolling?

- iOS 16.6.1
- Tested Firefox, Safari and Vivaldi

**Comment by benpate** [comment]
Thank you for this.  My "fast click" code was a little too aggressive -- especially on touch devices.  I've scaled this back, and it should now work correctly on mobile phones and tablets.

The update has been posted, so please let me know that this is working correctly for you?

**Comment by meljoann** [comment]
Hi, thanks!

Hmm, no sorry I deleted the cache and everything, but it's still doing unwanted clicks for me? Seems like it does scroll a little more though, before it clicks in... not sure!

**Comment by benpate** [comment]
Sorry for the back and forth.  I've just posted another update (and made sure that this one "took").  It's working for me on my iPhone, so I'm pretty confident that it'll work for you, now, too.

**Comment by meljoann** [comment]
Ah beautiful, it works great now! Thanks so much :)

**Comment by benpate** [comment]
Fantastic!  And, thank you for letting me know.  

Systems like this are super complicated.  It's very important to me that we get the details right, but it's nearly impossible to check every single situation.  That's why brave, real-world users like you are so important, to help find the things we can do better.

Please keep sharing the things you need from Bandwagon to make it better (both big and small)
