### ISSUE TITLE
Allow artists to keep an unpublished draft of an album by adding a "publish" button

### ISSUE THREAD

**Issue by docpop** [EmissarySocial/bandwagon#13]
It appears that an album is live on my site from the minute I started adding tracks to it. It would be nice to have a way to add songs and make changes before the album is publicly viewable. 

This could be done by adding a button on the edit album page that allows the user to control when the album is publicly viewable. This button could be listed as "Publish" (or "Published" to match the past tense verbage of the "Featured" button). 
![Screenshot 2024-09-11 at 9 13 03 AM](https://github.com/user-attachments/assets/7846d220-7f1b-4e40-9ca5-c5979b088131)

**Comment by benpate** [comment]
Thank you, yes.  This is a great suggestion.

Fortunately, Emissary already has a "publish" feature.. I'm just not using it for albums/songs. So, it should be pretty simple to use.  I'll post an update here when this is ready :)

**Comment by benpate** [comment]
Done.

All new albums will start off as "unpublished" and will be clearly labeled that it's not visible to your fans.  

<img width="1189" alt="Screenshot 2024-09-12 at 9 10 36 PM" src="https://github.com/user-attachments/assets/f7c4f8d1-196e-4c65-8879-653038bc24b4">

I've manually marked all existing albums as already "published" so that you don't have to go back and touch stuff that's already working.  If there are some albums you're not ready to share, yet, just click the "unpublish" button at the top of the album page and it'll be hidden for now.

This status also works on the album directory on the front page.  So any albums you've published will be listed there, as well.

Does this work for you?
