### ISSUE TITLE
Title does not show in Mastodon

### ISSUE THREAD

**Issue by ethicalrevolution** [EmissarySocial/bandwagon#31]
When creating a new post in Bandwagon the title of the post does not come through at all in the Mastodon post. 

Expected outcome: title to come through in bold as it does when creating a post on wordpress and federating via the ActivityPub plugin (e.g. see screenshot showing 'Shannon Curtis Live!' showing in bold at the top of the post on Mastodon, which was the title of the post in Wordpress).

**Comment by ethicalrevolution** [comment]
![Screenshot from 2024-10-28 08-16-52](https://github.com/user-attachments/assets/90e6de03-48ec-4d54-9cb7-9f0c988478ab)

**Comment by benpate** [comment]
Sorry to let this sit unanswered.  Just for you to know, I'm looking into our options on this.  

Every ActivityPub server behaves a little different.  And though Mastodon is probably the best app to target, it's not the only one that we're trying to "split the difference" on.

I think we have some options to make Mastodon show things better (if you're nerdy, I'm looking at sending "Article" types instead of "Notes") but I still have to learn about the repercussions if we do this.

I'll let you know how it goes :)
