### ISSUE TITLE
Low contrast font on Personale Links page

### ISSUE THREAD

**Issue by docpop** [EmissarySocial/bandwagon#8]
When adding personal links, I had a hard time seeing the text that I had written in the fields. The text is white on a light blue background.

It would be nice to have black text on white, or white text on black for those fields. 
![Screenshot 2024-09-10 at 2 01 32 PM](https://github.com/user-attachments/assets/78660859-e846-4e17-a3f0-ccc070adb45f)

**Comment by benpate** [comment]
Yeah, this is a mistake.  Thanks for showing me. 

I've gone to great lengths to support both "light mode" and "dark mode", to automatically detect this from your custom colors, and to automatically pick the best text color for your custom color scheme.

The problem here is that I've hard coded light blue into the widget, so it looks like trash with a dark mode background.

I'll get this sorted out pretty quick.

(BTW, you must be in tech, Dr., because your bug reports are *perfect*)

**Comment by benpate** [comment]
This is now working correctly in dark mode.  As I mentioned, there was essentially a "hard coded" color in there that expected light mode, and broke miserably in dark mode.  You may need to clear your browser cache to see this, but it's there.  I swear :)
